---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD004: false                  # Unordered list style
MD007:
  indent: 2                   # Unordered list indentation
MD013:
  line_length: 4000           # Every viewer has wordwrap.... why do we care how long a line is unless they all are supposed to fit on one screen, which they won't,
MD020: false                  # This was flagging the Usage headings that are ubiquitous in library readme's.
MD026:
  punctuation: ".,;:!。，；:"  # List of not allowed
MD024: false                  # more trouble than it's worth
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading
MD037: false                  # Allow spaces around around emphacis marks because they are probably just rendering as the characters!
MD046: false                  # allow both indented and fenced code blocks

#################
# Rules by tags #
#################
blank_lines: false  # Error on blank lines
