call omake tinyxy2
call omake tinyxy4
call omake tinyxy6
call omake tinyxy7
call omake tinyxy2alt
call omake tinyxy4alt
call omake tinyxy6alt
call omake tinyxy7alt
call omake tinyxy2rst
call omake tinyxy6rst
call omake tinyxy6rst
call omake tinyxy7rst
call omake tinyxy2altrst
call omake tinyxy4altrst
call omake tinyxy6altrst
call omake tinyxy7altrst
