call omake tinyxy2
call omake tinyxyz
call omake tinyxy2alt
call omake tinyxyzalt
call omake tinyxy2rst
call omake tinyxyzrst
call omake tinyxy2altrst
call omake tinyxyzaltrst
call omake tinyxy21sec
call omake tinyxyz1sec
call omake tinyxy2alt1sec
call omake tinyxyzalt1sec
call omake xplained817
call omake xplained416
call omake curiosity1607
