name: Check Links

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-links.yml"
      - "**.md"
  pull_request:
    paths:
      - ".github/workflows/check-links.yml"
      - "**.md"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by changes to the linked sites.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: yes
          config-file: './.github/workflows/mlc_config.json'
